SELECT TOP (1000) [CherID]
      ,[Name]
      ,[Sex]
      ,[Gmail]
      ,[Phone]
  FROM [TesId].[dbo].[Cher2]
SELECT TOP (1000) [stuID]
      ,[Name]
      ,[sex]
      ,[DOB]
  FROM [TesId].[dbo].[Gattime1]
